name: speak_sphere
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  dotted_border: ^2.1.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  sizer: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/

  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/font/JosefinSans-Regular.ttf
        - asset: assets/font/JosefinSans-Bold.ttf
          weight: 700
