 List<String> interests = [
    "Studies",
    "Reading",
    "Technologies",
    "Travel",
    "Psychology",
    "Gaming",
    "TV/Movies",
    "Sports",
    "Languages",
    "Fashion",
    "Fitness",
    "Pets",
    "Food",
    "Climate Change",
    "Self-Care",
    "Work life",
    "Culture",
    "Design",
    "Sociology",
    "Music",
    "Outdoor",
    "Networking",
    "Romance",
    "Shopping",
    "Sight-seeing",
  ];